from __future__ import annotations

from enum import Enum


class OrderStatus(str, Enum):
    NOT_READY = "NOT_READY"
    READY_UNASSIGNED = "READY_UNASSIGNED"
    ASSIGNED_READY = "ASSIGNED_READY"
    PICKED = "PICKED"
    DELIVERED = "DELIVERED"
    CANCELED = "CANCELED"


class DroneMode(str, Enum):
    IDLE = "IDLE"
    FLYING_TO_PICKUP = "FLYING_TO_PICKUP"
    FLYING_TO_DROPOFF = "FLYING_TO_DROPOFF"
    FLYING_TO_STATION = "FLYING_TO_STATION"
    PICKUP_SERVICE = "PICKUP_SERVICE"
    DROPOFF_SERVICE = "DROPOFF_SERVICE"
    CHARGING = "CHARGING"


class TaskType(str, Enum):
    PICKUP = "PICKUP"
    DROPOFF = "DROPOFF"


class EventType(str, Enum):
    ORDER_ARRIVAL = "ORDER_ARRIVAL"
    ORDER_READY = "ORDER_READY"
    DISPATCH_EPOCH = "DISPATCH_EPOCH"
    ARRIVE_MERCHANT = "ARRIVE_MERCHANT"
    PICKUP_FINISH = "PICKUP_FINISH"
    ARRIVE_CUSTOMER = "ARRIVE_CUSTOMER"
    DROPOFF_FINISH = "DROPOFF_FINISH"
    ARRIVE_STATION = "ARRIVE_STATION"
    CHARGE_FINISH = "CHARGE_FINISH"
    WEATHER_CHANGE = "WEATHER_CHANGE"


class WeatherState(str, Enum):
    CALM = "CALM"
    NORMAL = "NORMAL"
    WINDY = "WINDY"
    RAIN = "RAIN"
    STORM = "STORM"


EVENT_PRIORITIES: dict[EventType, int] = {
    EventType.ORDER_READY: 10,
    EventType.WEATHER_CHANGE: 20,
    EventType.CHARGE_FINISH: 30,
    EventType.DISPATCH_EPOCH: 40,
    EventType.ARRIVE_MERCHANT: 50,
    EventType.PICKUP_FINISH: 60,
    EventType.ARRIVE_CUSTOMER: 70,
    EventType.DROPOFF_FINISH: 80,
    EventType.ARRIVE_STATION: 90,
    EventType.ORDER_ARRIVAL: 100,
}
